### ISSUE TITLE
Add Node version compatibility

### ISSUE THREAD

**Issue by MattiSG** [egoist/nswatch#8]
Hi,

I tried to add `nswatch` to a project through the `package.json`.

At first, with `node@0.10`, it wouldn't even install (use of `const`).
With `node@4`, the scripts are run on startup but file changes don't trigger any task run.
I can't test with `node@7` because some of my dependencies are not compatible.

The code is available at [`agile-france/site-dessins#nswatch`](https://github.com/agile-france/site-dessins/tree/nswatch), and the issue can be reproduced with:

```sh
git clone https://github.com/agile-france/site-dessins.git
cd site-dessins
npm install
sleep 15 && echo '/* modified */' >> app/css/main.css &
npm run dev
```

If this is not a bug, then the compatible Node versions should at least be documented in an `engines` field of `nswatch`'s `package.json`.

In any case, thanks for publishing this module!  :)

**Comment by egoist** [comment]
Hmm, the minimal supported node version is `4` and is set in `package.json`

It looks you're watching `./app/css/*` but these files do not exist?

**Comment by egoist** [comment]
It actually works for me under node 4
<img width="521" alt="2017-02-20 9 52 03" src="https://cloud.githubusercontent.com/assets/8784712/23127690/e8a6a296-f7b6-11e6-8749-fbe3c32b981d.png">

**Comment by egoist** [comment]
by the way, `app/css` does not exist so `echo '/* modified */' >> app/css/main.css` would fail

**Comment by MattiSG** [comment]
😓

Sorry for the noise, yet another case of the stupid “I looked at all the complex possible causes but not the simplest one” — I had indeed just forgotten one directory in the path description.

Thanks for the help, adding `nswatch` in https://github.com/agile-france/site-dessins/pull/16!

**Comment by egoist** [comment]
Hmm, I see that you already have gulp, so why not `gulp.watch`?

**Comment by MattiSG** [comment]
Because I consider that kind of task managers as an anti pattern, don't know `gulp`, and wanted to try `nswatch`  :wink:
